/**
 * @fileoverview gRPC-Web generated client stub for garaga
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.27.3
// source: garage.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.garaga = require('./garage_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.garaga.GaragaServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.garaga.GaragaServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.garaga.GaragaRequest,
 *   !proto.garaga.GaragaResponse>}
 */
const methodDescriptor_GaragaService_GenerateCalldata = new grpc.web.MethodDescriptor(
  '/garaga.GaragaService/GenerateCalldata',
  grpc.web.MethodType.UNARY,
  proto.garaga.GaragaRequest,
  proto.garaga.GaragaResponse,
  /**
   * @param {!proto.garaga.GaragaRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.garaga.GaragaResponse.deserializeBinary
);


/**
 * @param {!proto.garaga.GaragaRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.garaga.GaragaResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.garaga.GaragaResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.garaga.GaragaServiceClient.prototype.generateCalldata =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/garaga.GaragaService/GenerateCalldata',
      request,
      metadata || {},
      methodDescriptor_GaragaService_GenerateCalldata,
      callback);
};


/**
 * @param {!proto.garaga.GaragaRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.garaga.GaragaResponse>}
 *     Promise that resolves to the response
 */
proto.garaga.GaragaServicePromiseClient.prototype.generateCalldata =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/garaga.GaragaService/GenerateCalldata',
      request,
      metadata || {},
      methodDescriptor_GaragaService_GenerateCalldata);
};


module.exports = proto.garaga;

