/**
 * @fileoverview gRPC-Web generated client stub for prove_service
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.27.3
// source: prove_serivce.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.prove_service = require('./prove_service_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.prove_service.ProveServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.prove_service.ProveServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.prove_service.ProveRequest,
 *   !proto.prove_service.ProveResponse>}
 */
const methodDescriptor_ProveService_prove = new grpc.web.MethodDescriptor(
  '/prove_service.ProveService/prove',
  grpc.web.MethodType.UNARY,
  proto.prove_service.ProveRequest,
  proto.prove_service.ProveResponse,
  /**
   * @param {!proto.prove_service.ProveRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.prove_service.ProveResponse.deserializeBinary
);


/**
 * @param {!proto.prove_service.ProveRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.prove_service.ProveResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.prove_service.ProveResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.prove_service.ProveServiceClient.prototype.prove =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/prove_service.ProveService/prove',
      request,
      metadata || {},
      methodDescriptor_ProveService_prove,
      callback);
};


/**
 * @param {!proto.prove_service.ProveRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.prove_service.ProveResponse>}
 *     Promise that resolves to the response
 */
proto.prove_service.ProveServicePromiseClient.prototype.prove =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/prove_service.ProveService/prove',
      request,
      metadata || {},
      methodDescriptor_ProveService_prove);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.prove_service.EmptyRequest,
 *   !proto.prove_service.ProveResponse>}
 */
const methodDescriptor_ProveService_get_public_key = new grpc.web.MethodDescriptor(
  '/prove_service.ProveService/get_public_key',
  grpc.web.MethodType.UNARY,
  proto.prove_service.EmptyRequest,
  proto.prove_service.ProveResponse,
  /**
   * @param {!proto.prove_service.EmptyRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.prove_service.ProveResponse.deserializeBinary
);


/**
 * @param {!proto.prove_service.EmptyRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.prove_service.ProveResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.prove_service.ProveResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.prove_service.ProveServiceClient.prototype.get_public_key =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/prove_service.ProveService/get_public_key',
      request,
      metadata || {},
      methodDescriptor_ProveService_get_public_key,
      callback);
};


/**
 * @param {!proto.prove_service.EmptyRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.prove_service.ProveResponse>}
 *     Promise that resolves to the response
 */
proto.prove_service.ProveServicePromiseClient.prototype.get_public_key =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/prove_service.ProveService/get_public_key',
      request,
      metadata || {},
      methodDescriptor_ProveService_get_public_key);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.prove_service.EmptyRequest,
 *   !proto.prove_service.EmptyResponse>}
 */
const methodDescriptor_ProveService_ping = new grpc.web.MethodDescriptor(
  '/prove_service.ProveService/ping',
  grpc.web.MethodType.UNARY,
  proto.prove_service.EmptyRequest,
  proto.prove_service.EmptyResponse,
  /**
   * @param {!proto.prove_service.EmptyRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.prove_service.EmptyResponse.deserializeBinary
);


/**
 * @param {!proto.prove_service.EmptyRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.prove_service.EmptyResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.prove_service.EmptyResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.prove_service.ProveServiceClient.prototype.ping =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/prove_service.ProveService/ping',
      request,
      metadata || {},
      methodDescriptor_ProveService_ping,
      callback);
};


/**
 * @param {!proto.prove_service.EmptyRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.prove_service.EmptyResponse>}
 *     Promise that resolves to the response
 */
proto.prove_service.ProveServicePromiseClient.prototype.ping =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/prove_service.ProveService/ping',
      request,
      metadata || {},
      methodDescriptor_ProveService_ping);
};


module.exports = proto.prove_service;

